name: godot-custom-build

services:
  builder:
    build: 
      context: .
      args:
        GIT_COMMIT: a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0
        BUILD_DIR: /home
        DXC_LINK: https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2405/dxc_2024_05_24.zip
        MESA_LINK: https://github.com/godotengine/godot-nir-static/releases/download/23.1.9/godot-nir-23.1.9.zip
        PIX_LINK: https://www.nuget.org/api/v2/package/WinPixEventRuntime/1.0.240308001
    volumes:
      - type: bind
        source: ./build
        target: /build
    image: godot-custom-build:latest