name: godot-build-windows

services:
  winbuilder:
    image: godot-build-windows:latest
    build: 
      context: .
      args:
        BUILD_DIR: \build
        GIT_COMMIT: a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0
        BUILD_TOOLS_URL: https://aka.ms/vs/17/release/vs_buildtools.exe
        PYTHON_URL: https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe
        DXC_URL: https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2405/dxc_2024_05_24.zip
        MESA_URL: https://github.com/godotengine/godot-nir-static/releases/download/23.1.9/godot-nir-23.1.9.zip
        PIX_URL: https://www.nuget.org/api/v2/package/WinPixEventRuntime/1.0.240308001
    environment:
      BUILD_DIR: \build
    volumes:
      - type: bind
        source: D:\Projects and Repositories\Godot Building\godot
        target: c:\build\godot
    develop:
      watch:
        - action: sync
          path: .\build scripts
          target: c:\build
